name: CI

on: [push, pull_request]

jobs:
  build:
    name: apriltag_ros
    runs-on: ubuntu-latest

    container:
      image: ubuntu:22.04

    steps:
    - uses: actions/checkout@v4

    - uses: ros-tooling/setup-ros@v0.7

    - uses: ros-tooling/action-ros-ci@v0.3
      with:
        package-name: apriltag_ros
        target-ros2-distro: humble
        vcs-repo-file-url: .github/deps.repos
